CREATE FUNCTION FN_DOANHTHU_THEONHOMHANG(
@NGAYD DATETIME,
@NGAYC DATETIME)
RETURNS TABLE AS RETURN
SELECT C.IDNHOM,D.TENNHOM,SUM(A.THANHTIEN) AS THANHTIEN
FROM tb_CHUNGTU_CT A, tb_CHUNGTU B, tb_HANGHOA C, TB_NHOMHH D
WHERE A.KHOA = B.KHOA
AND A.BARCODE = C.BARCODE
AND C.IDNHOM = D.IDNHOM
AND B.LCT IN (3,4)
AND B.NGAY>=CONVERT(DATETIME,@NGAYD,103)
AND B.NGAY<CONVERT(DATETIME,@NGAYC,103)
GROUP BY C.IDNHOM,D.TENNHOM

--1:nhap mua,2:xuatnb,nhapnb,3:xuatsi,4:banle