//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TONKHO
    {
        public System.Guid KHOA { get; set; }
        public Nullable<int> NAMKY { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> KY { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public string BARCODE { get; set; }
        public string LG_DAU { get; set; }
        public string LG_NHAPMUA { get; set; }
        public Nullable<int> LG_NHAPNB { get; set; }
        public Nullable<int> LG_XUATNB { get; set; }
        public Nullable<int> LG_XUATSI { get; set; }
        public Nullable<int> LG_BANLE { get; set; }
        public Nullable<int> LG_CUOI { get; set; }
        public Nullable<double> TRIGIA { get; set; }
        public Nullable<double> TIEN_CUOI { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string MACTY { get; set; }
        public string BARCODE { get; set; }
        public string LG_NHAPMUA { get; set; }
        public Nullable<int> LG_NHAPNB { get; set; }
        public Nullable<int> LG_XUATNB { get; set; }
        public Nullable<int> LG_XUATSI { get; set; }
        public Nullable<int> LG_BANLE { get; set; }
        public Nullable<double> TRIGIA { get; set; }
        public Nullable<double> TIEN_CUOI { get; set; }
    }
}
